include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - always_use_package_imports
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - prefer_final_locals
    - sort_child_properties_last
